### ISSUE TITLE
Doesn't work with Vivaldi

### ISSUE THREAD

**Issue by kevingosse** [mjisaak/skilling-champion-extension#18]
The extension doesn't seem to work with Vivaldi. Everything seems functional at first, but the link doesn't get copied to the clipboard.

It looks like Vivaldi doesn't see that the extension needs clipboard access:
![image](https://user-images.githubusercontent.com/11140081/119256596-baae4f00-bbc1-11eb-88b7-f0d59e6a2e5a.png)

I'm not sure why. I don't think Vivaldi uses a different manifest format.

**Comment by mjisaak** [comment]
Hi Kevin,

Sorry to hear that. Vivaldi is not yet supported/tested. Unfortunately, I am currently very busy, maybe someone will find the problem or I find the time to look at it.
