### ISSUE TITLE
Doubling CreatorIDs

### ISSUE THREAD

**Issue by rappen** [mjisaak/skilling-champion-extension#27]
## Expect
Replace to my CreatorID.

## What happens
If I open a site with already a CreatorID and create a new link with CreatorID - it will be added instead of replace.

## Example
Click to page:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.metadata.entitymetadata?view=dynamics-general-ce-9&WT.mc_id=BA-MVP-5002470

Click the tool to add my CreatorID, result is:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.metadata.entitymetadata?view=dynamics-general-ce-9&WT.mc_id=BA-MVP-5002470&WT.mc_id=BA-MVP-5002475

Click a few more times:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.metadata.entitymetadata?view=dynamics-general-ce-9&WT.mc_id=BA-MVP-5002470&WT.mc_id=BA-MVP-5002475&WT.mc_id=BA-MVP-5002475&WT.mc_id=BA-MVP-5002475

**Comment by mjisaak** [comment]
Hi @rappen 

Thank you for submitting this bug. I can reproduce it and will fix it ASAP.

BR,
Martin

**Comment by mjisaak** [comment]
@rappen I fixed the bug with release [1.4.4](https://github.com/mjisaak/skilling-champion-extension/releases/tag/v1.4.4) and uploaded the new Version to the Edge, Chrome and Firefox marketplace. Should be available within the next few hours...
BR
Martin

**Comment by rappen** [comment]
Thanks,
I am not too great with Chrome (I only "use it") - the extension says version 1.4.4 - but I don't get the last version... it stays at 1.4.3.
Should I just wait for a while...?
The buttons can only uninstall, nothing to "Update" it. (I feel a bit stupid...)

**Comment by rappen** [comment]
Yep, I thought so.
👍
