### ISSUE TITLE
Update to version 1.5.0 in Edge Add-ons

### ISSUE THREAD

**Issue by maisondasilva** [mjisaak/skilling-champion-extension#39]
Update to version 1.5.0 in Edge Add-ons

Another thing I noticed is that the IDs are generated WT.mc_id=XXX_XXXXXX but I see that normally the WT is lowercase, you could change this to vim as default ?wt.mc_id=XXX_XXXXXX

Thank you for this extension, it is very useful and I recommend it to other people!

Thanks Maison

**Comment by mjisaak** [comment]
Hi Maison,

the update 1.5.0 contains the migration to Manifest version 3, I have not been able to install it yet, but hopefully I will do so in the next few weeks. 

I am not sure about the lowercase version of WT. In general, it should not matter but like in every document I see (including the MVP Docs & Learn Champion emails) it is written in uppercase: ?WT.mc_id

**Comment by maisondasilva** [comment]
Ok, no problem Thanks for the response, is it possible for you to add a language option? I would love to have a Portuguese version of Brazil! Although I could fork this, but adding it to your version is welcome!

**Comment by mjisaak** [comment]
What you mean with a Portuguese version of Brazil?

**Comment by maisondasilva** [comment]
Display according to the browser language, is this possible?

**Comment by mjisaak** [comment]
@maisondasilva 
Yes, this is already implemented. In the extension option, you can set whether you want to make English URLs (en-us)  or language-specific URLs (xx-xx) language-neutral. 

![image](https://github.com/mjisaak/skilling-champion-extension/assets/8446917/29e55c39-9330-4429-b9a5-fa5d8416c1f1)

That means, if you copy a page URL with your CreatorID like this one:
https://learn.microsoft.com/en-us/microsoft-365-copilot/

It will not only append your CreatorID but also remove the language identifier:
https://learn.microsoft.com/microsoft-365-copilot/?WT.mc_id=...

If you now open this link, the page will be displayed depending on the language of your browser.
Btw, the version 1.5.0 is now live in Edge. 
BR,
Martin
